### PR TITLE
fix(module): rc9 compatibility issues

### LINKED ISSUE #90: Module @nuxtjs/algolia is disabled due to incompatibility issues
### Version

@nuxtjs/algolia: 1.1.1
nuxt: 3.0.0-r.c.9

### Reproduction Link

https://github.com/marcusarnfast/Incompatibility-issues-with-Algolia

### Steps to reproduce

Yarn add 

### What is Expected?

Algolia module to work

### What is actually happening?

Module @nuxtjs/algolia is disabled due to incompatibility issues:                                                                                                                                                   
 - [nuxt] Nuxt version `^3.0.0 || ^2.16.0` is required but currently using `3.0.0-rc.9`

### PR DESCRIPTION
**Pull request by Intevel**
Will fix #90 and #91 
@Baroshem 

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Lexpeartha** [comment]
Not a module author, but it might be helpful to add a message in docs that says rc 9 of nuxt is required  version in order to function?

**Comment by lukaszflorczak** [comment]
It looks that `addAutoImportDir()` is also (soft) depreciated and changed to `addImportsDir()`

Source: https://github.com/nuxt/framework/pull/7158

**Comment by Intevel** [comment]
> 

The autoImports hook was deprecated, or am I wrong?

**Comment by lukaszflorczak** [comment]
They renamed utils:
> Updated kit utils:
> Soft deprecated (type only) `addAutoImport` to `addImports` and `addAutoImportDir` to `addImportsDir` for consistency

**Comment by Intevel** [comment]
Ah okay thank you, I will update this.

**Comment by Baroshem** [comment]
Hey folks, 

thanks for this PR. I am back from holidays and will merge this PR and release a new version so that you could use it without errors **tomorrow**.

Thanks for the patience.

**Review by Baroshem — APPROVED** [review]

**Comment by Baroshem** [comment]
Guys, the new version has been released. You can verify now if it works correctly. I have tested it in several nuxt projects and it is working correctly :)

**Pull request merged**
